//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindLink.Recruitment.MyChat.UI.Console {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MindLink.Recruitment.MyChat.UI.Console.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified, sensitive information such as credit card numbers and telephone numbers will be censored..
        /// </summary>
        internal static string CensorSensitiveInformationOptionDescription {
            get {
                return ResourceManager.GetString("CensorSensitiveInformationOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified, only messages which contain the keyword will be considered..
        /// </summary>
        internal static string ContentKeywordFilterOptionDescription {
            get {
                return ResourceManager.GetString("ContentKeywordFilterOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation exported from &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string ConversationExportedToFileFormat {
            get {
                return ResourceManager.GetString("ConversationExportedToFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified, the result will contain a report with the most active users in the conversation..
        /// </summary>
        internal static string GenerateMostActiveUsersReportOptionDescription {
            get {
                return ResourceManager.GetString("GenerateMostActiveUsersReportOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input file to process..
        /// </summary>
        internal static string InputFileOptionDescription {
            get {
                return ResourceManager.GetString("InputFileOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords to censor in the resulting messages..
        /// </summary>
        internal static string KeywordsToCensorOptionDescription {
            get {
                return ResourceManager.GetString("KeywordsToCensorOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified, the user of each message will be obfuscated..
        /// </summary>
        internal static string ObfuscateUserOptionDescription {
            get {
                return ResourceManager.GetString("ObfuscateUserOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output file to write the result into..
        /// </summary>
        internal static string OutputFileOptionDescription {
            get {
                return ResourceManager.GetString("OutputFileOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If specified, only messages of this user will be considered..
        /// </summary>
        internal static string UserFilterOptionDescription {
            get {
                return ResourceManager.GetString("UserFilterOptionDescription", resourceCulture);
            }
        }
    }
}
