//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyChatWeb.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        // CODEGEN: Generating message contract since the wrapper name (DownloadRequest) of message DownloadRequest does not match the default value (DownloadFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DownloadFile", ReplyAction="http://tempuri.org/IService1/DownloadFileResponse")]
        MyChatWeb.ServiceReference1.RemoteFileInfo DownloadFile(MyChatWeb.ServiceReference1.DownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DownloadFile", ReplyAction="http://tempuri.org/IService1/DownloadFileResponse")]
        System.Threading.Tasks.Task<MyChatWeb.ServiceReference1.RemoteFileInfo> DownloadFileAsync(MyChatWeb.ServiceReference1.DownloadRequest request);
        
        // CODEGEN: Generating message contract since the operation UploadFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UploadFile", ReplyAction="http://tempuri.org/IService1/UploadFileResponse")]
        MyChatWeb.ServiceReference1.UploadFileResponse UploadFile(MyChatWeb.ServiceReference1.RemoteFileInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UploadFile", ReplyAction="http://tempuri.org/IService1/UploadFileResponse")]
        System.Threading.Tasks.Task<MyChatWeb.ServiceReference1.UploadFileResponse> UploadFileAsync(MyChatWeb.ServiceReference1.RemoteFileInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TriggerConversation", ReplyAction="http://tempuri.org/IService1/TriggerConversationResponse")]
        string TriggerConversation(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TriggerConversation", ReplyAction="http://tempuri.org/IService1/TriggerConversationResponse")]
        System.Threading.Tasks.Task<string> TriggerConversationAsync(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetChartData", ReplyAction="http://tempuri.org/IService1/GetChartDataResponse")]
        string GetChartData(string file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetChartData", ReplyAction="http://tempuri.org/IService1/GetChartDataResponse")]
        System.Threading.Tasks.Task<string> GetChartDataAsync(string file);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string FileName;
        
        public DownloadRequest() {
        }
        
        public DownloadRequest(string FileName) {
            this.FileName = FileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFileInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoteFileInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public RemoteFileInfo() {
        }
        
        public RemoteFileInfo(string FileName, long Length, System.IO.Stream FileByteStream) {
            this.FileName = FileName;
            this.Length = Length;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        public UploadFileResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MyChatWeb.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MyChatWeb.ServiceReference1.IService1>, MyChatWeb.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyChatWeb.ServiceReference1.RemoteFileInfo MyChatWeb.ServiceReference1.IService1.DownloadFile(MyChatWeb.ServiceReference1.DownloadRequest request) {
            return base.Channel.DownloadFile(request);
        }
        
        public long DownloadFile(ref string FileName, out System.IO.Stream FileByteStream) {
            MyChatWeb.ServiceReference1.DownloadRequest inValue = new MyChatWeb.ServiceReference1.DownloadRequest();
            inValue.FileName = FileName;
            MyChatWeb.ServiceReference1.RemoteFileInfo retVal = ((MyChatWeb.ServiceReference1.IService1)(this)).DownloadFile(inValue);
            FileName = retVal.FileName;
            FileByteStream = retVal.FileByteStream;
            return retVal.Length;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyChatWeb.ServiceReference1.RemoteFileInfo> MyChatWeb.ServiceReference1.IService1.DownloadFileAsync(MyChatWeb.ServiceReference1.DownloadRequest request) {
            return base.Channel.DownloadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyChatWeb.ServiceReference1.RemoteFileInfo> DownloadFileAsync(string FileName) {
            MyChatWeb.ServiceReference1.DownloadRequest inValue = new MyChatWeb.ServiceReference1.DownloadRequest();
            inValue.FileName = FileName;
            return ((MyChatWeb.ServiceReference1.IService1)(this)).DownloadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyChatWeb.ServiceReference1.UploadFileResponse MyChatWeb.ServiceReference1.IService1.UploadFile(MyChatWeb.ServiceReference1.RemoteFileInfo request) {
            return base.Channel.UploadFile(request);
        }
        
        public void UploadFile(string FileName, long Length, System.IO.Stream FileByteStream) {
            MyChatWeb.ServiceReference1.RemoteFileInfo inValue = new MyChatWeb.ServiceReference1.RemoteFileInfo();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            MyChatWeb.ServiceReference1.UploadFileResponse retVal = ((MyChatWeb.ServiceReference1.IService1)(this)).UploadFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyChatWeb.ServiceReference1.UploadFileResponse> MyChatWeb.ServiceReference1.IService1.UploadFileAsync(MyChatWeb.ServiceReference1.RemoteFileInfo request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyChatWeb.ServiceReference1.UploadFileResponse> UploadFileAsync(string FileName, long Length, System.IO.Stream FileByteStream) {
            MyChatWeb.ServiceReference1.RemoteFileInfo inValue = new MyChatWeb.ServiceReference1.RemoteFileInfo();
            inValue.FileName = FileName;
            inValue.Length = Length;
            inValue.FileByteStream = FileByteStream;
            return ((MyChatWeb.ServiceReference1.IService1)(this)).UploadFileAsync(inValue);
        }
        
        public string TriggerConversation(string[] args) {
            return base.Channel.TriggerConversation(args);
        }
        
        public System.Threading.Tasks.Task<string> TriggerConversationAsync(string[] args) {
            return base.Channel.TriggerConversationAsync(args);
        }
        
        public string GetChartData(string file) {
            return base.Channel.GetChartData(file);
        }
        
        public System.Threading.Tasks.Task<string> GetChartDataAsync(string file) {
            return base.Channel.GetChartDataAsync(file);
        }
    }
}
